import { useState } from 'react'
import { ArrowLeft, ArrowRight, ArrowUpRight, Check } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { templates } from '../data/templates'
import TemplatePreview from '../components/TemplatePreview'

export default function TemplateDetail() {
  const { slug } = useParams()
  const template = templates.find((item) => item.slug === slug)
  const [copied, setCopied] = useState(false)
  if (!template) return <main className="page-width not-found"><span className="eyebrow">404 / NOT IN THE COLLECTION</span><h1>Nothing here<br /><em>just yet.</em></h1><Link className="text-action" to="/templates"><ArrowLeft size={15} /> Back to templates</Link></main>
  const copyLink = async () => { await navigator.clipboard.writeText(window.location.href); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }
  return <main className="detail-page page-width"><Link className="back-link" to="/templates"><ArrowLeft size={15} /> All templates</Link><div className="detail-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> {template.category.toUpperCase()} / TEMPLATE {template.number}</div><h1>{template.name}</h1><p>{template.description}</p></div><div className="detail-actions">{template.demoUrl ? <a className="button button-outline" href={template.demoUrl} target="_blank" rel="noreferrer">Live demo <ArrowUpRight size={15} /></a> : <span className="button button-outline disabled-button" aria-disabled="true">Live demo <ArrowUpRight size={15} /><span className="action-note">Coming soon</span></span>}<span className="button button-dark disabled-button" aria-disabled="true">{template.price ? `Get template · $${template.price}` : 'Coming soon'} <ArrowRight size={15} /></span></div></div><TemplatePreview template={template} controls className="detail-preview" /><div className="detail-body"><section className="detail-overview"><span className="eyebrow">THE IDEA</span><p>{template.longDescription}</p><button className="text-action share-button" onClick={copyLink}>{copied ? <Check size={15} /> : <ArrowUpRight size={15} />}{copied ? 'Link copied' : 'Share this template'}</button></section><aside className="detail-facts"><div className="fact-block"><h2>Designed for</h2><ul>{template.designedFor.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="fact-block"><h2>Features</h2><ul>{template.features.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="fact-block"><h2>Built with</h2><div className="tag-list">{template.techStack.map((item) => <span key={item}>{item}</span>)}</div></div></aside><section className="detail-lists"><div><span className="eyebrow">MAKE IT YOURS</span><h2>Customization</h2><ul>{template.customization.map((item) => <li key={item}>{item}</li>)}</ul></div><div><span className="eyebrow">IN THE PACKAGE</span><h2>What's included</h2><ul>{template.included.map((item) => <li key={item}>{item}</li>)}</ul></div></section></div><div className="detail-next"><span className="eyebrow">KEEP LOOKING</span><Link to="/templates">Explore the collection <ArrowRight size={16} /></Link></div></main>
}
